# 使用github action自动打包start.py为exe文件
name: 'Build'
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build
        run: |
          pyinstaller start.py --onefile --noconsole
      - name: Upload
        # 上传到release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.UPLOAD_TOKEN }}
          file: dist/start.exe
          tag: 'latest'
          overwrite: true
          file_glob: true
